// This file is @generated by prost-build.
/// Tenant scope. `user_id` is required; `session_id` narrows to a
/// per-session shelf when set, otherwise the tenant's global shelf
/// is targeted.
///
/// `team_id` is the billing-key (subscription owner). Set by trusted
/// callers (managed bridge, cloud/api) from the `x-team-id` JWT claim
/// so memory-related `record_usage("memories", ±1)` calls bill against
/// the user's real team instead of falling back to `team=user`.
/// Legacy callers that don't set this field still work — the server
/// falls back to `user_id` and emits a `tracing::warn!` flagging the
/// caller as un-upgraded.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Scope {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub session_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub team_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryEntry {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
    /// Free-form metadata (tags, source, provenance). Round-trips
    /// through the underlying `adaptive::types::Entry.metadata`.
    #[prost(map = "string, string", tag = "3")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Server-side wall-clock at insert. ISO-8601.
    #[prost(string, tag = "4")]
    pub created_at: ::prost::alloc::string::String,
    /// Score is only populated on search responses.
    #[prost(double, optional, tag = "5")]
    pub score: ::core::option::Option<f64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryAddRequest {
    #[prost(message, optional, tag = "1")]
    pub scope: ::core::option::Option<Scope>,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MemoryAddResponse {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemorySearchRequest {
    #[prost(message, optional, tag = "1")]
    pub scope: ::core::option::Option<Scope>,
    #[prost(string, tag = "2")]
    pub query: ::prost::alloc::string::String,
    #[prost(int32, optional, tag = "3")]
    pub limit: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "4")]
    pub min_score: ::core::option::Option<f64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemorySearchResponse {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<MemoryEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MemoryListRequest {
    #[prost(message, optional, tag = "1")]
    pub scope: ::core::option::Option<Scope>,
    #[prost(int32, optional, tag = "2")]
    pub limit: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryListResponse {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<MemoryEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MemoryDeleteRequest {
    #[prost(message, optional, tag = "1")]
    pub scope: ::core::option::Option<Scope>,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MemoryDeleteResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MemoryStatsRequest {
    #[prost(message, optional, tag = "1")]
    pub scope: ::core::option::Option<Scope>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MemoryStatsResponse {
    #[prost(int64, tag = "1")]
    pub count: i64,
    /// ISO-8601 timestamp of the most recent insert; empty when count=0.
    #[prost(string, tag = "2")]
    pub last_added_at: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
}
